### ISSUE TITLE
Fresh install doesn't properly create tables

### ISSUE THREAD

**Issue by YouveGotMeowxy** [JakobST1n/RSS-watcher#2] opened 2023-08-18 00:34 UTC
Running the docker container

- created my db and db user
- fired up the container
- looked into the initial tables the container created and columns indeed get created
- container refuses to start because it didn't create a `0` id:

![Screenshot 2023-08-17 192723](https://github.com/JakobST1n/RSS-watcher/assets/39491297/58b09d2e-8e6e-4bd0-8e3d-1eb5f24c0dfa)

**Comment by YouveGotMeowxy** [comment] 2023-08-18 00:46
Then I manually changed the `id` in the above screenshot to `0` and restarted teh container. Now I get this error upon attempting to start:

> [2023-08-18T00:43:07Z INFO  rss_watcher] Starting rss-watcher
[2023-08-18T00:43:07Z INFO  rss_watcher::database] Bootstrapping database
[2023-08-18T00:43:07Z INFO  rss_watcher::database] Connected to database
[2023-08-18T00:43:07Z WARN  rss_watcher::database] Running migrations to v2
[2023-08-18T00:43:07Z ERROR rss_watcher::database] Could not run database migration to v2...! (MySqlError { ERROR 1142 (42000): ALTER command denied to user 'oc_rsswatcher'@'10.0.40.173' for table `rss_watcher`.`rss-watcher-feeds` }

But I already had given that user full permissions from the start, even before the initial table was created by the container:

![image](https://github.com/JakobST1n/RSS-watcher/assets/39491297/2e7594d9-0663-4b59-abfb-4a46ee146e35)

**Comment by YouveGotMeowxy** [comment] 2023-08-18 02:01
Well after digging into the source code it turns out that it's a _requirement_ that the db be named `rss_watcher`, even though the instructions indicate that any db name will work. After that, after the first run it still puts the wrong id in, so it needs to manually be set to 0. after that it'll start up.

**Comment by JakobST1n** [comment] 2023-09-08 16:50
Hi, that is clearly a oversight :) The database is selected dynamically, so there is no reason it needs to be used in that query. I haven`t had time to test the change, but it _should_ be fine.

**Comment by JakobST1n** [comment] 2023-09-08 17:12
I looks like there has been a change since I wrote this code, such that you cannot by default insert with id=0 in a auto_increment field. Which makes this fix slightly harder. The previous commit fixes the last issue you mentioned, but not the first.

Just changing this ID is a bit scary, as I have no idea how many or few people is using this package. 

This can be resolved in mysql by setting the sql_mode before the insert, but a better solution would probably be to attempt to retrieve both `id=0` and `id=1`, and see which of them has `version` in the `url` column. 
A even better alternative would maybe be to change the id column to a VARCHAR, and use UUID's instead of auto_increment. and use a id like `SCHEMA_VERSION` or something like that.
That would however probably break frontends if anyone has designed it for this, it would certainly break mine. 

If you have any thoughts, please leave them :)

**Comment by JakobST1n** [comment] 2023-09-08 17:43
I think this is the most logical solution tbh, it would be better to change to UUID. But I really don't want to make breaking changes, another solution would also be to just make another migration where everyone will have that row as id=1. But that would require moving all other ids, which would also be somewhat of a hassle...

**Comment by JakobST1n** [comment] 2023-09-08 17:59
Should be fixed with [v.0.3.3](https://github.com/JakobST1n/RSS-watcher/releases/tag/v0.3.3),

**Closed as completed** 2023-09-08 18:23 UTC
